name: balaghnyv1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.1.7
  flutter_local_notifications: ^16.1.0
  rxdart: ^0.27.7

  # ✅ Firebase SDK (All must be ^3.x compatible)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.0
  firebase_storage: ^12.4.5

  # ✅ Others
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  uuid: ^4.5.1
  intl: ^0.20.2
  timeago: ^3.7.1
  fl_chart: ^1.0.0
  firebase_messaging: ^15.2.5
  location: ^8.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/balaghny_logo.png
    - assets/images/logo.png
    - assets/images/onboarding.png



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
